apiVersion: apps/v1
kind: Deployment
metadata:
  name: curler
spec:
  selector:
    matchLabels:
      app: curler
  template:
    metadata:
      labels:
        app: curler
    spec:
      containers:
      - name: curler
        image: busybox:1.32.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "while sleep 1; do wget http://nginx -O /dev/null && echo ok; done"]
