apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcs-curler
spec:
  selector:
    matchLabels:
      app: mcs-curler
  template:
    metadata:
      labels:
        app: mcs-curler
    spec:
      containers:
      - name: mcs-curler
        image: busybox:1.32.1
        imagePullPolicy: IfNotPresent
        # I know this isn't MCS... but MCS redirects to HTTPS which busybox's wget doesn't implement - so I used apache.org instead.
        command: ["/bin/sh", "-c", "while sleep 1; do wget http://apache.org -O /dev/null && echo ok; done"]
